[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
wpmwar_program = "6YnWTXBsLgFcEygmvA9r6FzVWu5gLxfgcpw4vXiQPUBJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.gorbagana.wtf"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
initialize-global-stats = "yarn ts-node ./scripts/initialize_global_stats.ts"
